<?php if( isset($this->post) &&  count($this->post)):?>
	<?php for($i=0;$i<count($this->post);$i++):?>
	<section id='posts' class="posts">
		<article class="post" id="<?php echo($this->post[$i]['nickname']);?>">
			<div class="descripcion">
				<div class="detalles">
					<h2 class="titulo">
						<?php echo($this->post[$i]['Contenido']);?>
					</h2>
					<p class="autor">
						por <a href="#"><?php echo($this->post[$i]['nickname']);?></a>
					</p>

					<div class="hidden" id="<?php echo $i ?>">
						<p>mensaje retwitteado con exito </p>
					</div>
					<?php if(count($this->post[$i][5])!=0): ?>
					<p>retweet por <?php echo implode(' ; ',$this->post[$i][5]) ?></p>
					<?php endif ?>
					<p class="fecha">hace <strong><?php echo($this->post[$i]['postingTime']);?></strong> min</p>
				</div>
			</div>
			<div class="acciones">
				<div class="votos">
					<?php if($this->post[$i]['nickname']!=$this->user): ?>
					<a class="up" href="#" onclick="retweet('<?php echo($this->post[$i]['nickname']);?>','<?php echo $this->user ?>', '<?php echo($this->post[$i]['postingTime']);?>','<?php echo BASE_URL ?>','<?php echo $i?>')">retnott</a>
				<?php else: ?>
			<?php endif; ?>
					
				</div>
				<div class="datos">
					<?php if(count($this->post[$i][5])!=0): ?>
				<a class="comentarios" href="#"><?php echo($this->conteoretweet);?></a>				
				<?php endif?>
					
					<a class="estrellita" href="#"></a>
				</div>
			</div>
		</article>
	</section>
<?php endfor?>
<?php else:?>
<h2>No tienes nott</h2>
<?php endif?>