<?php if(isset($this->nombreUsuarioMicronott)): ?>
	<h1>Perfil del usuario <?php echo $this->nombreUsuarioMicronott ?></h1>
	<img src="<?php echo BASE_URL .  $this->foto['location']  ?>" alt="nombre <?php echo $this->nombreUsuarioMicronott ?>"/>
	<h4><?php echo $this->foto['caption']  ?></h4>
	<h2><?php echo $this->profile['userProfileDesc'] ?></h2>
<?php else: ?>
	<p>OPS parece que este usuario no existe</p>
<?php endif; ?>
