 <!--code for form-->
		<section id="form">
				<br/>				
		        <h1>Log in to your account</h1>
				<form name="login-form" id="smart-login" method="post" action="index.php">
					<input type="hidden" value="1" name="enviar"/>
					<fieldset id="smart-login-fields">
						<input id="username" name="username"type="text" placeholder="Username" required>
						<br/>
						<input id="password" name="password" type="password" placeholder="Password" required>
					</fieldset>
					<span class="password-reset"><a href="#">Forgot Your Password?</a></span><br/><br/><br/>
					<span class="cookie"><input type="checkbox" value="true">keep me login</span>
					<fieldset id="smart-login-actions">
						<input type="reset" id="reset" value="Reset">
						<input type="submit" id="login" value="Log in" >
					</fieldset>
					<br/>
	  			 </form>
    	</section>