<?php if(isset($this->nombreUsuarioMicronott)): ?>
	<h1>Perfil del usuario <?php echo $this->nombreUsuarioMicronott ?></h1>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
		Deserunt ad doloribus quas at aliquam repudiandae nihil. 
		Ut, necessitatibus, doloremque laborum id est reiciendis 
		repellendus minima ratione numquam sed quod incidunt.
	</p>
<?php else: ?>
	<p>OPS parece que este usuario no existe</p>
<?php endif; ?>
