<?php if( isset($this->usuariosencontrados)):?>
 <!--&&  count($this->usuariosencontrados)):-->
	<?php for($i=0;$i<count($this->usuariosencontrados);$i++):?>
	<form action="visitante/verPerfil" method="post">
	<ul>
	<li>	
	<label><?php echo($this->usuariosencontrados[$i]['nickname']);?></label>
	<input type="hidden" value="<?php echo($this->usuariosencontrados[$i]['iduser']);?>" name="usuario"/>
	<input type="hidden" value="<?php echo($this->usuariosencontrados[$i]['nickname']);?>" name="nickname"/>
	 <input type="submit" value="Ver nott">
	 </li>
	</ul>	
	</form>
	<?php endfor; ?>
	<?php else:?>		
		<p>No existen usuarios registrados en la base de datos</p>
	
	<?php endif?>