<head>
    <link rel="stylesheet" type="text/css" href="<?php echo $_layoutParams['ruta_css'] ?>styleRegister.css">    
 </head>
<section id="formMain">
		<form class="register" method="POST" action="registro">
        <input type="hidden" value="1" name="enviar">
		<h2>Register</h2>

	<input type="text" class="text-field" placeholder="First Name"  id="fName" name="name" required/>
    <input type="text" class="text-field" placeholder="Last Name" id="lName" name="lastname" required/>
    <input type="text" class="text-field" placeholder="NickName" id="nickname" name="nickname"  required/>
    <input type="email" class="text-field" placeholder="E-mail" name="email" id="email" onkeyup="check_withAjax()" required />
    <input type="password" class="text-field" placeholder="Password" id="password" name="password" required/>
    <input type="password" class="text-field" placeholder="Repeat Password" id="password2" name="confirm" required />
    
    <input type="submit" value="Register Account"  />

</form>
	</section>
<?php if(isset($this->prueba)) echo $this->prueba; ?>
<script src="<?php echo BASE_URL; ?>views/registro/js/ajaxConnection.js"></script>