<head>
    <link rel="stylesheet" type="text/css" href="<?php echo $_layoutParams['ruta_css'] ?>styleRegister.css">    
 </head>
<section id="formMain">
		<form class="register" method="POST" action="registro">
        <input type="hidden" value="1" name="enviar">
		<h2 id="h2">Register</h2>

	<input type="text" class="text-field" placeholder="First Name"  id="fName" name="name" required/>
    <input type="text" class="text-field" placeholder="Last Name" id="lName" name="lastname" required/>
    <input type="text" class="text-field" placeholder="NickName" id="nickname" name="nickname"  required/>
    <?php if( isset($this->usuariosencontrados)):?>
    </br></br>
    <div id="div1">
        <label id="usuario">Nickname ya fue registrado</label>    
    <!--<input value="Nickname ya fue registrado" id="usuario" name="usuario" size="25"/>    -->
    </div>
    
    <?php else:?>
    <input type="hidden" name="usuario"/>
    <?php endif?>
    
    <input type="email" class="text-field" placeholder="E-mail" name="email" id="email" onkeyup="check_withAjax()" required />
    <?php if( isset($this->mailencontrado)):?>
    </br></br>
    <div id="div2">
    <label id="mail">Email ya fue registrado</label>    
    <!--<input value="Email ya fue registrado" id="mail" name="mail" size="25"/>-->
    </div>    
    <?php else:?>
    <input type="hidden" name="mail"/>
    <?php endif?>
    <input type="password" class="text-field" placeholder="Password" id="password" name="password" required/>
    <input type="password" class="text-field" placeholder="Repeat Password" id="password2" name="confirm" required /></br></br>
    
    <input id="botonregister" type="submit" value="Register Account"/>

</form>
	</section>
<?php if(isset($this->prueba)) echo $this->prueba; ?>
<script src="<?php echo BASE_URL; ?>views/registro/js/ajaxConnection.js"></script>