<?php if( isset($this->usuariosencontrados)):?>
 <!--&&  count($this->usuariosencontrados)):-->
	<?php for($i=0;$i<count($this->usuariosencontrados);$i++):?>
	<form action="#" method="post">
	<ul>
	<li>	
	<label><?php echo($this->usuariosencontrados[$i]['nickname']);?></label>
	<input type="hidden" value="<?php echo($this->usuariosencontrados[$i]['idUser']);?>" name="usuario"/>
	<input type="hidden" value="<?php echo($this->usuariosencontrados[$i]['nickname']);?>" name="nickname"/>
	 <input type="submit" value="Ver nott">
	 </li>
	</ul>	
	</form>
	<?php endfor; ?>
	<?php else:?>		
		<p>No estas siguiendo a nadie :(</p>
	
	<?php endif?>